---
name: shellcheck
on:
  push:
    branches:
      - master
    paths-ignore: [ 'paper/**', 'sandbox/**' ]
  pull_request:
    branches:
      - master
    paths-ignore: [ 'paper/**', 'sandbox/**' ]
concurrency:
  group: shellcheck-${{ github.ref }}
  cancel-in-progress: true
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
